services:
  app_service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5050 --reload
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - ./dump:/app/dump  # Ensure the data directory is mounted
    ports:
      - "5050:5050"
  
